// Common topics for KS3 and KS4 by subject

export const topics = {
  english: {
    ks3: [
      'Reading comprehension - fiction',
      'Reading comprehension - non-fiction',
      'Creative writing - narrative',
      'Creative writing - descriptive',
      'Persuasive writing',
      'Letter writing',
      'Poetry analysis',
      'Shakespeare introduction',
      'Grammar and punctuation',
      'Spelling patterns',
      'Speaking and listening',
      'News report writing',
    ],
    ks4: [
      'GCSE Literature - Of Mice and Men',
      'GCSE Literature - An Inspector Calls',
      'GCSE Literature - Macbeth',
      'GCSE Literature - Romeo and Juliet',
      'GCSE Literature - A Christmas Carol',
      'GCSE Literature - Poetry anthology',
      'GCSE Language - Paper 1 fiction',
      'GCSE Language - Paper 2 non-fiction',
      'Transactional writing',
      'Comparative essay writing',
      'Unseen poetry',
      'Spoken language endorsement',
    ],
  },
  maths: {
    ks3: [
      'Number operations',
      'Fractions, decimals, percentages',
      'Ratio and proportion',
      'Basic algebra',
      'Solving equations',
      'Coordinates and graphs',
      'Angles and shapes',
      'Area and perimeter',
      'Data handling',
      'Probability',
      'Sequences',
      'Negative numbers',
    ],
    ks4: [
      'GCSE - Linear equations',
      'GCSE - Quadratic equations',
      'GCSE - Simultaneous equations',
      'GCSE - Trigonometry',
      'GCSE - Pythagoras theorem',
      'GCSE - Circle theorems',
      'GCSE - Probability',
      'GCSE - Statistics',
      'GCSE - Transformations',
      'GCSE - Vectors',
      'GCSE - Algebraic fractions',
      'GCSE - Compound measures',
    ],
  },
  science: {
    ks3: [
      'Cells and organisation',
      'Body systems',
      'Reproduction',
      'Forces and motion',
      'Energy',
      'Waves - light and sound',
      'Electricity',
      'Atoms and elements',
      'Chemical reactions',
      'Earth and atmosphere',
      'Ecosystems',
      'Genetics basics',
    ],
    ks4: [
      'GCSE Biology - Cell biology',
      'GCSE Biology - Organisation',
      'GCSE Biology - Infection and response',
      'GCSE Biology - Bioenergetics',
      'GCSE Chemistry - Atomic structure',
      'GCSE Chemistry - Bonding',
      'GCSE Chemistry - Quantitative chemistry',
      'GCSE Chemistry - Chemical changes',
      'GCSE Physics - Energy',
      'GCSE Physics - Electricity',
      'GCSE Physics - Forces',
      'GCSE Physics - Waves',
    ],
  },
} as const;

export const taskTypeLabels: Record<string, string> = {
  worksheet: 'Worksheet',
  reading: 'Reading task',
  writing: 'Writing task',
  practical: 'Practical activity',
  discussion: 'Discussion/verbal task',
};

export const workingLevelLabels: Record<string, string> = {
  eyfs: 'EYFS (Reception level)',
  ks1: 'KS1 (Years 1-2 level)',
  ks2: 'KS2 (Years 3-6 level)',
  ks3: 'KS3 (Years 7-9 level)',
  ks4: 'KS4 (Years 10-11 level)',
};

export const strategyLabels: Record<string, string> = {
  'chunking': 'Chunking',
  'backward-chaining': 'Backward Chaining',
  'task-analysis': 'Task Analysis',
  'prompt-fading': 'Prompt Fading',
  'visual-supports': 'Visual Supports',
  'errorless-learning': 'Errorless Learning',
};
